# Generated by Django 2.2.7 on 2019-11-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191126_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='isPubliseh',
            new_name='isPublished',
        ),
    ]
